spring:
   profiles: prod
   datasource:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: 
      username: 
      password: 
   jpa:
      hibernate:
         ddl-auto: none
         #ddl-auto: create-drop
      properties:
         hibernate:
            dialect: org.hibernate.dialect.SQLServer2012Dialect #every database have varies dialect. Configuration connection databe. Ex: mysql
            jdbc:
               lob:
                  non_contextual_creation: true
            enable_lazy_load_no_trans: true
            event:
              merge:
                  entity_copy_observer: allow #fix bug : Multiple represent in same entity
app:
   url: 