spring:
   profiles: prod
   datasource:
      driver-class-name: org.postgresql.Driver
      url:
      username: 
      password: 
   jpa:
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect #every database have varies dialect. Configuration connection databe. Ex: mysql
            jdbc:
               lob:
                  non_contextual_creation: true
app:
   url: 